default['cassandra']['path'] = '/home/ubuntu/cassandra/apache-cassandra-3.0.12/conf'
default['cassandra']['rack'] = 'rack2'
default['cassandra']['data_center'] = 'dc2'
default['cassandra']['seed_node'] = '0.0.0.0'
default['cassandra']['endpoint_snitch'] = 'GossipingPropertyFileSnitch'
